// src/ai/flows/suggest-relevant-suppliers.ts
'use server';
/**
 * @fileOverview This file defines a Genkit flow to suggest relevant suppliers based on a business plan.
 *
 * The flow takes a business plan as input and returns a list of suggested suppliers with their details,
 * including an AI-generated summary and a combined recommendation.
 *
 * @param {SuggestRelevantSuppliersInput} input - The input data for the flow, including the business plan and optional supplier tool selection.
 * @returns {Promise<SuggestRelevantSuppliersOutput>} A promise that resolves to the output of the flow, containing a list of suggested suppliers.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const SuggestRelevantSuppliersInputSchema = z.object({
  businessPlan: z
    .string()
    .describe('The business plan of the entrepreneur.'),
  businessLocation: z
    .string()
    .describe('The location of the business (e.g., city, country).'),
  supplierToolSelection: z
    .string()
    .optional()
    .describe(
      'Optional selection of supplier types to consider for recommendations.'
    ),
});
export type SuggestRelevantSuppliersInput = z.infer<
  typeof SuggestRelevantSuppliersInputSchema
>;

const SupplierSchema = z.object({
  name: z.string().describe('The name of the supplier.'),
  description: z.string().describe('A description of the supplier.'),
  contactInfo: z.string().describe('The contact information of the supplier.'),
  location: z.string().describe('The location of the supplier.'),
  specialOffers: z.string().optional().describe('Any special offers from the supplier.'),
  summaryIA: z.string().describe('A brief, engaging summary generated by the AI, explaining why this supplier is a good fit for the user\'s business.')
});

const SuggestRelevantSuppliersOutputSchema = z.object({
  suppliers: z.array(SupplierSchema).describe('A list of suggested suppliers.'),
  combinedRecommendation: z.string().optional().describe('A suggestion on how to combine the top suppliers for a complete solution.'),
});
export type SuggestRelevantSuppliersOutput = z.infer<
  typeof SuggestRelevantSuppliersOutputSchema
>;

export async function suggestRelevantSuppliers(
  input: SuggestRelevantSuppliersInput
): Promise<SuggestRelevantSuppliersOutput> {
  return suggestRelevantSuppliersFlow(input);
}

const suggestRelevantSuppliersPrompt = ai.definePrompt({
  name: 'suggestRelevantSuppliersPrompt',
  input: {schema: SuggestRelevantSuppliersInputSchema},
  output: {schema: SuggestRelevantSuppliersOutputSchema},
  prompt: `You are an AI business advisor tasked with providing hyper-relevant supplier recommendations to entrepreneurs. Your entire output MUST be in Spanish.

  **Phase 1: Semantic Analysis & Sentiment Analysis**
  First, analyze the user's business plan to understand its core needs. Extract key concepts, products, and services required.
  **Crucially, perform sentiment and quality analysis on the user's text.** If the user specifiesqualities like "good quality", "cheap", "eco-friendly", "fast delivery", use these adjectives to heavily influence the recommendations.
  - Business Plan: {{{businessPlan}}}
  - Business Location: {{{businessLocation}}}
  {{#if supplierToolSelection}}
  - Specific Supplies Mentioned: {{{supplierToolSelection}}}
  {{/if}}

  **Phase 2: Supplier Recommendation & Scoring**
  Based on your analysis, suggest a list of 3-5 highly relevant suppliers. For each supplier, you MUST:
  1.  Provide basic details: name, description, contactInfo, location, and any specialOffers.
  2.  Generate a "summaryIA": A dynamic, personalized summary explaining EXACTLY why this supplier is a great fit for the user's specific business idea and quality requirements. For example: "Este proveedor es ideal para tu cafetería, ya que ofrece granos de café de especialidad de alta calidad y tostados artesanalmente, perfectos para el ambiente que buscas."
  3.  **Crucially, prioritize suppliers in or very near the specified business location. Proximity is a key scoring factor.** A supplier in another state is less relevant than one in the same city. Match the sentiment/quality requests. A high-rating supplier is a good proxy for "good quality".

  **Phase 3: Combined Strategy**
  After listing the suppliers, provide a "combinedRecommendation". This should be a short paragraph suggesting how the top 2-3 suppliers could work together to provide a comprehensive solution. For example: "Para un lanzamiento exitoso, podrías combinar los granos de 'Café del Sur' con el mobiliario de 'Diseño Rústico' para crear el ambiente perfecto."

  Return the final output as a JSON object matching the defined schema.
  `,
});

const suggestRelevantSuppliersFlow = ai.defineFlow(
  {
    name: 'suggestRelevantSuppliersFlow',
    inputSchema: SuggestRelevantSuppliersInputSchema,
    outputSchema: SuggestRelevantSuppliersOutputSchema,
  },
  async input => {
    const {output} = await suggestRelevantSuppliersPrompt(input);
    return output!;
  }
);
