'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/customize-supplier-recommendations.ts';
import '@/ai/flows/suggest-relevant-suppliers.ts';
import '@/ai/flows/analyze-business-idea.ts';
import '@/ai/flows/generate-action-plan.ts';
import '@/ai/flows/generate-digital-identity.ts';
import '@/ai/flows/generate-logo-from-prompt.ts';
import '@/ai/flows/generate-marketing-campaign.ts';
import '@/ai/flows/generate-resource-plan.ts';
import '@/ai/flows/analyze-existing-business.ts';
import '@/ai/flows/generate-task-audio.ts';
import '@/ai/flows/generate-campaign-plan.ts';
import '@/ai/flows/analyze-breakeven-point.ts';
import '@/ai/flows/generate-module-audio.ts';
import '@/ai/flows/regenerate-brand-elements.ts';
import '@/ai/flows/generate-campaign-task-audio.ts';
import '@/ai/flows/generate-optimized-image.ts';
